[build]
  publish = "dist/portfolio-frontend/browser"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Handle SPA routing
[[redirects]]
  from = "/about"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/experience"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/projects"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/skills"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/education"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 4200
  publish = "dist/portfolio-frontend/browser"
